OK added --enable-testing so I can build but not run the tests and I added --enable-site-tests to enable the sse site operations

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_VERSION='1.0.0'
 PACKAGE_STRING='sse_wilson_dslash 1.0.0'
 PACKAGE_BUGREPORT='bjoo@jlab.org'
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE BUILD_QDP_TESTS_TRUE BUILD_QDP_TESTS_FALSE QDPXX_CONFIG SSEXX_AUX_CFLAGS SSEXX_AUX_LDFLAGS SSEXX_AUX_LIBS QMP_CONFIG SCALAR_SINGLE_TRUE SCALAR_SINGLE_FALSE SCALAR_DOUBLE_TRUE SCALAR_DOUBLE_FALSE PARSCALAR_SINGLE_TRUE PARSCALAR_SINGLE_FALSE PARSCALAR_DOUBLE_TRUE PARSCALAR_DOUBLE_FALSE BUILD_QDP_PACKERS_TRUE BUILD_QDP_PACKERS_FALSE QMT_CFLAGS QMT_LDFLAGS QMT_LIBS BUILD_QMT_TRUE BUILD_QMT_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE BUILD_SITE_TESTS_TRUE BUILD_SITE_TESTS_FALSE RUN_TESTS_TRUE RUN_TESTS_FALSE BUILD_QDP_TESTS_TRUE BUILD_QDP_TESTS_FALSE QDPXX_CONFIG SSEXX_AUX_CFLAGS SSEXX_AUX_LDFLAGS SSEXX_AUX_LIBS QMP_CONFIG SCALAR_SINGLE_TRUE SCALAR_SINGLE_FALSE SCALAR_DOUBLE_TRUE SCALAR_DOUBLE_FALSE PARSCALAR_SINGLE_TRUE PARSCALAR_SINGLE_FALSE PARSCALAR_DOUBLE_TRUE PARSCALAR_DOUBLE_FALSE BUILD_QDP_PACKERS_TRUE BUILD_QDP_PACKERS_FALSE QMT_CFLAGS QMT_LDFLAGS QMT_LIBS BUILD_QMT_TRUE BUILD_QMT_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -823,6 +823,11 @@ Optional Features:
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-parallel-arch=<arch>
                           Build Assembler for parallel architecture <arch>
+  --enable-testing        Enable make check to automatically run tests, rather
+                          than just build them
+  --enable-site-tests     Enable building of site-ops tests. These still use
+                          inline assembler so may not be suitable for all
+                          compilers
   --enable-precision=<precision>
                           Build Assembler for <precision> precision. Possible
                           values are single and double (default is single)
@@ -3439,6 +3444,19 @@ if test "${enable_parallel_arch+set}" = set; then
 
 fi;
 
+# Check whether --enable-testing or --disable-testing was given.
+if test "${enable_testing+set}" = set; then
+  enableval="$enable_testing"
+   do_tests="${enableval}"
+
+fi;
+
+# Check whether --enable-site-tests or --disable-site-tests was given.
+if test "${enable_site_tests+set}" = set; then
+  enableval="$enable_site_tests"
+   site_tests="${enableval}"
+
+fi;
 
 # Check whether --enable-precision or --disable-precision was given.
 if test "${enable_precision+set}" = set; then
@@ -3481,6 +3499,46 @@ fi;
 
 
 
+if test "X${site_tests}X" = "XyesX" ;
+then
+ { echo "$as_me:$LINENO:  Building Site Tests  " >&5
+echo "$as_me:  Building Site Tests  " >&6;}
+else
+ { echo "$as_me:$LINENO:  Not building site tests  " >&5
+echo "$as_me:  Not building site tests  " >&6;}
+fi
+
+
+if  test "X${site_tests}X" == "XyesX"  ; then
+  BUILD_SITE_TESTS_TRUE=
+  BUILD_SITE_TESTS_FALSE='#'
+else
+  BUILD_SITE_TESTS_TRUE='#'
+  BUILD_SITE_TESTS_FALSE=
+fi
+
+
+if test "X${do_tests}X" == "XyesX" ;
+then
+ { echo "$as_me:$LINENO:  Enabling automatic running of tests for make check " >&5
+echo "$as_me:  Enabling automatic running of tests for make check " >&6;}
+else
+ { echo "$as_me:$LINENO:  make check will make but not run the tests " >&5
+echo "$as_me:  make check will make but not run the tests " >&6;}
+fi
+
+
+
+if  test "X${do_tests}X" == "XyesX"  ; then
+  RUN_TESTS_TRUE=
+  RUN_TESTS_FALSE='#'
+else
+  RUN_TESTS_TRUE='#'
+  RUN_TESTS_FALSE=
+fi
+
+
+
 
 if  test "X${QDPXX_GIVEN}X" == "XyesX"  ; then
   BUILD_QDP_TESTS_TRUE=
@@ -3489,6 +3547,10 @@ else
   BUILD_QDP_TESTS_TRUE='#'
   BUILD_QDP_TESTS_FALSE=
 fi
+
+
+
+
 
 
 if test "X${QDPXX_GIVEN}X" = "XyesX"; then
@@ -4624,6 +4686,20 @@ echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_SITE_TESTS_TRUE}" && test -z "${BUILD_SITE_TESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_SITE_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_SITE_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${RUN_TESTS_TRUE}" && test -z "${RUN_TESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"RUN_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"RUN_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_QDP_TESTS_TRUE}" && test -z "${BUILD_QDP_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_QDP_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -5262,6 +5338,10 @@ s,@am__fastdepCC_FALSE@,$am__fastdepCC_FALSE,;t t
 s,@CXXDEPMODE@,$CXXDEPMODE,;t t
 s,@am__fastdepCXX_TRUE@,$am__fastdepCXX_TRUE,;t t
 s,@am__fastdepCXX_FALSE@,$am__fastdepCXX_FALSE,;t t
+s,@BUILD_SITE_TESTS_TRUE@,$BUILD_SITE_TESTS_TRUE,;t t
+s,@BUILD_SITE_TESTS_FALSE@,$BUILD_SITE_TESTS_FALSE,;t t
+s,@RUN_TESTS_TRUE@,$RUN_TESTS_TRUE,;t t
+s,@RUN_TESTS_FALSE@,$RUN_TESTS_FALSE,;t t
 s,@BUILD_QDP_TESTS_TRUE@,$BUILD_QDP_TESTS_TRUE,;t t
 s,@BUILD_QDP_TESTS_FALSE@,$BUILD_QDP_TESTS_FALSE,;t t
 s,@QDPXX_CONFIG@,$QDPXX_CONFIG,;t t
